### ISSUE TITLE
Parcours fichier dans example cassini.py

### ISSUE THREAD

**Issue by DarwinNE** [xoolive/python#4]
Bonjour,
   j'ai acheté le bouquin la semaine passée et je suis en train de le lire avec beaucoup de plaisir. Je crois que c'est *exactement* le type de bouquin dont j'avais besoin.

Je signale juste que je viens de cloner les exemples et je viens d'essayer l'example `01-bases/cassini/cassini.py`

~~~~
$ python rayon.py 
Traceback (most recent call last):
  File "rayon.py", line 11, in <module>
    with Path("../../data/triangles.txt").open("r") as fh:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../../data/triangles.txt'
~~~~

J'arrive à faire tourner l'exemple correctement avec deux petites corrections, car il manque à mon avis l'accès au répertoire `cassini` sous `data` :

~~~~
with Path("../../data/cassini/triangles.txt").open("r") as fh:
~~~~

et :

~~~~
with Path("../../data/cassini/inclinaisons.txt").open("r") as fh:
~~~~

Donc, pour résumer :

~~~~
$ git diff
diff --git a/01-bases/cassini/rayon.py b/01-bases/cassini/rayon.py
index 428972c..0b9350a 100644
--- a/01-bases/cassini/rayon.py
+++ b/01-bases/cassini/rayon.py
@@ -8,7 +8,7 @@ distances = dict()  # ①
 distances["Juvisy", "Villejuif"] = 5748  # ②
 distances["Sig.Nord", "Sig.Sud"] = 7928 + 5 / 6
 
-with Path("../../data/triangles.txt").open("r") as fh:
+with Path("../../data/cassini/triangles.txt").open("r") as fh:
     # Cette liste va stocker les valeurs intermédiaires par triangle
     triangle = list()
 
@@ -34,7 +34,7 @@ with Path("../../data/triangles.txt").open("r") as fh:
             triangle.clear()
 
 
-with Path("../../data/inclinaisons.txt").open("r") as fh:
+with Path("../../data/cassini/inclinaisons.txt").open("r") as fh:
     # On stocke dans total la longueur de la méridienne (en toises)
     total = 0
 ~~~~

Pour info :
~~~~
$ python
Python 3.7.12 (default, Jan  9 2022, 17:36:29) 
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
~~~~

**Comment by xoolive** [comment]
Bonjour et merci pour votre retour. C'est corrigé sur le site, je vais vérifier dans le pdf aussi, pour la prochaine impression (voire édition?)

N'hésitez pas à laisser des commentaires sur Amazon si le livre vous a plu!
